// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSentEmail(arg1) {
  return window['go']['app']['App']['AddSentEmail'](arg1);
}

export function BatchSendEmail(arg1, arg2) {
  return window['go']['app']['App']['BatchSendEmail'](arg1, arg2);
}

export function ClearEmailCredentials() {
  return window['go']['app']['App']['ClearEmailCredentials']();
}

export function ClearEmailHistory() {
  return window['go']['app']['App']['ClearEmailHistory']();
}

export function GetEmailCredentials() {
  return window['go']['app']['App']['GetEmailCredentials']();
}

export function GetEmailStats() {
  return window['go']['app']['App']['GetEmailStats']();
}

export function GetSentEmails() {
  return window['go']['app']['App']['GetSentEmails']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function SaveEmailCredentials(arg1) {
  return window['go']['app']['App']['SaveEmailCredentials'](arg1);
}

export function SearchEmails(arg1) {
  return window['go']['app']['App']['SearchEmails'](arg1);
}

export function SendEmail(arg1) {
  return window['go']['app']['App']['SendEmail'](arg1);
}

export function TestEmailConnection() {
  return window['go']['app']['App']['TestEmailConnection']();
}
