// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddSentEmail(arg1:app.SentEmail):Promise<void>;

export function BatchSendEmail(arg1:app.EmailData,arg2:Array<string>):Promise<{[key: string]: Error}>;

export function ClearEmailCredentials():Promise<void>;

export function ClearEmailHistory():Promise<void>;

export function GetEmailCredentials():Promise<app.EmailCredentials>;

export function GetEmailStats():Promise<{[key: string]: any}>;

export function GetSentEmails():Promise<Array<app.SentEmail>>;

export function Greet(arg1:string):Promise<string>;

export function SaveEmailCredentials(arg1:app.EmailCredentials):Promise<void>;

export function SearchEmails(arg1:string):Promise<Array<app.SentEmail>>;

export function SendEmail(arg1:app.EmailData):Promise<void>;

export function TestEmailConnection():Promise<void>;
